### PR TITLE
Data structures

### PR DESCRIPTION
**Pull request by kissik**
Hey! A brand new PR )

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @kissik ! Your PR removes files from your previous homework. Whenever we merge it, you first homework will be deleted. Please fix it. You need to start you new branch from master and avoid including not related changes. Feel free to close this PR and open a new one. Also, of course, feel free to ask for help if needed.

**Comment by OleksiyRudenko** [comment]
@kissik you may find this [guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b) helpful when getting rid of irrelevant commits

**Comment by kissik** [comment]
Hi, @AMashoshyna , @OleksiyRudenko !
Thank you very much for the code review)
I've tried to restore all removed files
Hope that it's correct..

**Comment by OleksiyRudenko** [comment]
@kissik let's take a look what the situation is and then fix it.
If you take a look at the **Files changed**
image

... and scroll down you will notice that the files from your other PR are still in place
image

Why that?
Let's take a look at the structure of your repo:
1) click **Insights** in repo top bar
2) click **Network** in insights left side bar
image

Drag the graph left until you see first commits of yours.
You will notice that two initial commits aa6bf18 and 0a6733d are both:
1) were committed into `master` branch in your fork
2) present in this PR
image
3) present in PR #11 (which is OK actually)
image

The items 2 and 3 are result from item 1 actions.

Your PR from branch `data-structures` contains all commits between branch tip and all the way down till the shared commit in base repo `master`.

To avoid the situations like that it is important to create a feature branch when on `master` before committing anything.

An extract from `README.md`
image

## How to fix

We need to reset the `master` in your fork first. In your local repo do the following:
```
git checkout 7b52ee6
git branch -f master
git checkout master
git push -f
```

The above is an implementation of this [part of the fixing guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b#honey-i-fixed-it)

Once done please let us know. And also post the output of `git remote -v` command.

**Comment by OleksiyRudenko** [comment]
@kissik your experience was a great source of insights for us. Based on that we have improved the contribution instructions. Thank you.

**Pull request closed without merging**
